title: Mass Nordic
description: Promoting cross country ski racing for Massachusetts high schoolers ages 14-18.
theme: just-the-docs
baseurl: ""
url: "https://massnordic.org"
search_enabled: true
color_scheme: massnordic
permalink: pretty
callouts:
  highlight:
    color: yellow
  update:
    title: Update
    color: blue    
plugins:
  - jekyll-target-blank
source: content
destination: _site
